# Generated by Django 2.2.4 on 2021-05-01 01:42

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(max_length=50)),
                ('invoice_reference', models.CharField(blank=True, default=None, max_length=50)),
                ('car_plate', models.CharField(blank=True, default=None, max_length=8)),
                ('accounts_receivables', models.DecimalField(decimal_places=2, max_digits=7)),
                ('balance', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=6)),
                ('accounts_payable', models.CharField(max_length=50)),
                ('inv_date', models.DateField()),
                ('submitter', models.CharField(default='Master', max_length=50)),
                ('financial_year', models.IntegerField(default=9999)),
                ('month', models.IntegerField(default=99)),
                ('cover', cloudinary.models.CloudinaryField(default='None', max_length=255)),
                ('log_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
