# Generated by Django 2.2.4 on 2021-05-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikar9', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='accounts_receivables',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='car_plate',
            field=models.CharField(blank=True, default='Admin', max_length=8),
        ),
    ]
