# Generated by Django 2.2.4 on 2021-05-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikar9', '0002_auto_20210507_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='submitter',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
