# Generated by Django 2.2.4 on 2021-05-07 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikar9', '0004_auto_20210507_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='log_date',
        ),
        migrations.AddField(
            model_name='invoice',
            name='log_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 7, 17, 12, 9, 62654)),
        ),
    ]
