# Generated by Django 2.2.4 on 2021-05-07 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikar9', '0005_auto_20210507_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='log_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
