# Generated by Django 2.2.4 on 2021-05-07 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invoice',
            new_name='LogRecord',
        ),
    ]
