# Generated by Django 2.2.4 on 2021-05-07 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_auto_20210507_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrecord',
            name='log_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
