# Generated by Django 2.2.4 on 2021-05-07 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_auto_20210507_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logrecord',
            old_name='log_datetime',
            new_name='log_dt',
        ),
    ]
