# Generated by Django 2.2.4 on 2021-05-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_auto_20210507_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrecord',
            name='log_dt',
            field=models.DateTimeField(blank=True),
        ),
    ]
