# Generated by Django 2.2.4 on 2021-05-07 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_auto_20210507_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logrecord',
            name='log_dt',
        ),
        migrations.AddField(
            model_name='logrecord',
            name='log_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
