# Generated by Django 2.2.4 on 2021-05-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarDeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_ref', models.CharField(max_length=10)),
                ('car_plate', models.CharField(max_length=8)),
                ('chassis_no', models.CharField(blank=True, default='none', max_length=25)),
                ('engine_no', models.CharField(blank=True, default='none', max_length=20)),
                ('current_owner', models.CharField(blank=True, default='none', max_length=30)),
                ('buyer', models.CharField(blank=True, default='none', max_length=30)),
                ('seller', models.CharField(blank=True, default='none', max_length=30)),
                ('referral', models.CharField(blank=True, default='none', max_length=30)),
            ],
        ),
    ]
